### ISSUE TITLE
No able unzip when the source file over 20mb folder when Zip file with LZMA2 and AesEncoder

### ISSUE THREAD

**Issue by szmulder** [weltkante/managed-lzma#16]
Modify the sandbox-7z project and add a file more than 20mb to the debug folder

Zip file with LZMA2 and AesEncoder
`node1 = encoder.CreateEncoder(new ManagedLzma.SevenZip.Writer.Lzma2EncoderSettings(new ManagedLzma.LZMA2.EncoderSettings() {  }));
                            node2 = encoder.CreateEncoder(new ManagedLzma.SevenZip.Writer.AesEncoderSettings(ManagedLzma.PasswordStorage.Create("test")));
 `

But I got exception when I try to readArchive
`Non-negative number required.
Parameter name: count`

trace:
`   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at ManagedLzma.LZMA2.Decoder.ReadOutputData(Byte[] buffer, Int32 offset, Int32 length) in C:\Project\Code\OpenSource\managed-lzma-master\shared\Compression\Lzma2\Decoder.cs:line 122
   at ManagedLzma.SevenZip.Reader.Lzma2ArchiveDecoder.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Project\Code\OpenSource\managed-lzma-master\shared\SevenZip\Decoders\Lzma2Decoder.cs:line 120
   at ManagedLzma.SevenZip.Reader.Lzma2ArchiveDecoder.OutputStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Project\Code\OpenSource\managed-lzma-master\shared\SevenZip\Decoders\Lzma2Decoder.cs:line 19
   at ManagedLzma.SevenZip.Reader.ArchiveSectionDecoder.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Project\Code\OpenSource\managed-lzma-master\shared\SevenZip\ArchiveDecoder.cs:line 207
   at ManagedLzma.SevenZip.Reader.DecodedStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Project\Code\OpenSource\managed-lzma-master\shared\SevenZip\ArchiveReader.cs:line 272
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at sandbox_7z.Program.Main() in C:\Project\Code\OpenSource\managed-lzma-master\sandbox-7z\Program.cs:line 169
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by weltkante** [comment]
Looks like a bug in how the decoder is called.

**Comment by weltkante** [comment]
Both fixes are included in alpha-6 on nuget
