### ISSUE TITLE
Decoding Exception

### ISSUE THREAD

**Issue by Zetanova** [weltkante/managed-lzma#24]
An archive was created with 7-zip.exe 9.20 and 18.01
with pw and multiple files.

A NotSupportedException is thrown on the first file stream:
   at ManagedLzma.SevenZip.Reader.BcjArchiveDecoder.DecodeInto(Byte[] buffer, Int32 offset, Int32 count)
   at ManagedLzma.SevenZip.Reader.BcjArchiveDecoder.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ManagedLzma.SevenZip.Reader.DecodedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)

**Comment by Zetanova** [comment]
without a password and a single file (700kb)
it is landing in a live lock where 1core is at 100%

**Comment by Zetanova** [comment]
LZMA and LZMA2 makes the same problems.
I reseted the 7-zip to the default compression settings.

Using .net4.6.2

**Comment by weltkante** [comment]
I'll take a look at the weekend and see if I can reproduce this behavior.

**Comment by weltkante** [comment]
I was able to reproduce both issues using 7zip 18.01 but it needs further investigation to determine what causes them. Maybe the updated 7zip/lzma codebase changed something and now triggers unexpected codepaths. I'll have a look at what code has changed in the recent releases.
