### ISSUE TITLE
sandbox-7z example code fails when archive contains empty file

### ISSUE THREAD

**Issue by ninad2110** [weltkante/managed-lzma#34]
If 7z archive already contains **folder/directory** it fails while reading **metadata**

- throws InvalidDataException exception in ArchiveMetadataReader.

Class: ArchiveMetadataReader
Method: ReadSectionDetails()
_System.IO.InvalidDataException: 'Found invalid data while decoding.'_

I created folder & archive using _managed-lzma/sandbox-7z/Program.cs_
Just added **ABCfolder\** (before line 116)  while creating archive, 7z file created successfully
I checked 7z by unpacking using other tools.

**Comment by weltkante** [comment]
I'll have a look, but it'd help if you can be more detailed on what you changed to produce this file (alternatively fork the repo and point me to your changes)

**Comment by ninad2110** [comment]
Thank you **weltkante**!

**Fork repo**: ninad2110 / managed-lzma
**Summary of changes**
1. Added sample folder in /sandbox-7z/
   Example/
                 Sample/ => Contains files to be archived
                 Pack/   => Sample folder will be archived to trial.7z  pack = true => Success
	         Unpack/ => Unpack trial.7z here pack=false, unpacking fails 
2. sandbox-7z is set as startup project
3. Modified \sandbox-7z\Program.cs 
		         pack = _true_ calls CreateArchieve() ==> **success**
		         pack = _false_ calls UnpackArchive() ==> **fails** with InvalidDataException exception

Note: Changed Compression\Lzma\EncoderSettings.cs to set level=1 (LZMA:16), but not related to above changes

**Comment by weltkante** [comment]
Doesn't look like it has anything to do with relative paths, but rather with empty files. Not sure what goes wrong there, either I'm encoding them wrong or the metadata reader is overly strict. I'll check in the next few days why the zero size check is in there.

**Comment by ninad2110** [comment]
- Checked by adding contents to empty file(s), and it worked.

- I have another 7z which isn't working, actually I tried to create similar 7z. To me, looks like some other issue with archived 7z file. I will do more tests and analyze and get back on this.

**Comment by weltkante** [comment]
> To me, looks like some other issue with archived 7z file.

The stack trace of the exception may be useful to classify it if you can't share the archive or repro it (though I can't guarantee I can fix it based on an exception stacktrace alone)

**Comment by ninad2110** [comment]
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Found invalid data while decoding.
  Source=managed-lzma
  StackTrace:
   at ManagedLzma.SevenZip.FileModel.ArchiveFileModelMetadataReader.ReadMetadata(Stream stream, PasswordStorage password) in D:\github\ninad2110\managed-lzma\shared\SevenZip\ArchiveFileModel.cs:line 303
   at sandbox_7z.Program.UnpackArchive(String archiveFileName, String targetDirectory, PasswordStorage password) in D:\github\ninad2110\managed-lzma\sandbox-7z\Program.cs:line 146
   at sandbox_7z.Program.UnpackArchive(String archiveFileName, String targetDirectory, String password) in D:\github\ninad2110\managed-lzma\sandbox-7z\Program.cs:line 132
   at sandbox_7z.Program.Main() in D:\github\ninad2110\managed-lzma\sandbox-7z\Program.cs:line 43
![debug](https://user-images.githubusercontent.com/73478213/115390757-3e100580-a1fc-11eb-8b3d-1cb99148bda0.png)

Added archive in 
Fork repo: ninad2110 / managed-lzma
Archive file : /sandbox-7z/Example/Pack/Data.7z

**Comment by weltkante** [comment]
The second exception is due to containing attribute metadata for a directory in a way which would not have been generated by the codebase I ported. In other words its a genuine "this data is not supposed to be here" exception. I'd have to investigate how newer versions of the 7zip codebase would treat it, but thats not going to happen anytime soon.
